### ISSUE TITLE
No such file or directory: '../colors/ray-1.jpeg'

### ISSUE THREAD

**Issue by bjornasm** [inconvergent/sand-creatures#1]
When running the main.py with no modifications, I get the following error as a response to line 36, get_colors('../colors/ray-1.jpeg'): 

No such file or directory: '../colors/ray-1.jpeg'

It seems like this file should be imported or should be included in this repo?

**Comment by inconvergent** [comment]
yeah, just point it to any image with colours, you think will work. these repos are in the state i leave them in as i work on them. i won't change it now.
